project_name: git-bump
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: git-bump
    ldflags:
      - -s -w
      - -X github.com/catatsuy/bento/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
release:
  prerelease: auto
