name: Go
on: [push]
jobs:
  setup:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18.x"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

  job1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: make check
        run: make check

  job2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: make vet
        run: make vet
